title: Orson Jiang
baseurl: ""
url: https://orsonjiang.com
description: "Another portfolio website by a software engineer and student."

# Build settings
search_enabled: false
footer_content: "Copyright © 2022-2025 Orson Jiang."
permalink: pretty

# External navigation links
nav_external_links:
    - title: GitHub Repository
      url: https://github.com/orsonjiang/orsonjiang.github.io
      hide_icon: false

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89a
ga_tracking: G-DXM302GVGM
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
    - jekyll-seo-tag

compress_html:
    clippings: all
    comments: all
    endings: all
    startings: []
    blanklines: false
    profile: false
    # ignore:
    #   envs: all
